name: sc-env
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.8 
    - scanpy
    - pip
    - pip:
        - scpopcorn
    - R=4.0.2
    - r-essentials
    - r-irkernel
    - r-seurat   
    - Jupyter
    - numpy
    - scipy
    - pandas
